channels:
- conda-forge
dependencies:
- python=3.9.6
- pip<=21.2.4
- pip:
  - mlflow==3.1.4
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - psutil==7.1.0
  - scikit-learn==1.3.2
  - scipy==1.13.1
name: mlflow-env
